/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inicio;

/**
 *
 * @author Mayela
 */
public class tablair extends javax.swing.JDialog {

    /**
     * Creates new form tablair
     */
    public tablair(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    }
        
        public tablair() {
        initComponents();
    }

//    public tablair() {
//        throw new UnsupportedOperationException("Not yet implemented");
//    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setMinimumSize(new java.awt.Dimension(13, 140));
        jPanel2.setPreferredSize(new java.awt.Dimension(58, 140));
        jPanel2.setLayout(new java.awt.GridLayout(7, 0));

        jLabel1.setText("DESDE");
        jPanel2.add(jLabel1);

        jTextField1.setText("1.00");
        jPanel2.add(jTextField1);

        jTextField2.setText("100000.01");
        jPanel2.add(jTextField2);

        jTextField3.setText("750000.01");
        jPanel2.add(jTextField3);

        jTextField4.setText("200000.01");
        jPanel2.add(jTextField4);

        jTextField5.setText("300000.01");
        jPanel2.add(jTextField5);

        jTextField6.setText("500000.01");
        jPanel2.add(jTextField6);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(7, 0));

        jLabel2.setText("HASTA");
        jPanel3.add(jLabel2);

        jTextField7.setText("75000.00");
        jPanel3.add(jTextField7);

        jTextField8.setText("100000.00");
        jPanel3.add(jTextField8);

        jTextField9.setText("200000.00");
        jPanel3.add(jTextField9);

        jTextField10.setText("300000.00");
        jPanel3.add(jTextField10);

        jTextField11.setText("500000.00");
        jPanel3.add(jTextField11);

        jTextField12.setText("MAS");
        jPanel3.add(jTextField12);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(7, 0));

        jLabel3.setText("IMPUESTO BASE");
        jPanel4.add(jLabel3);

        jTextField13.setText("0.00");
        jPanel4.add(jTextField13);

        jTextField14.setText("0.00");
        jPanel4.add(jTextField14);

        jTextField15.setText("2500.00");
        jPanel4.add(jTextField15);

        jTextField16.setText("7500.00");
        jPanel4.add(jTextField16);

        jTextField17.setText("37500.00");
        jPanel4.add(jTextField17);

        jTextField18.setText("87500.00");
        jPanel4.add(jTextField18);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(7, 0));

        jLabel4.setText("PORCENTAJE APLICABLE");
        jPanel5.add(jLabel4);

        jTextField19.setText("0%");
        jPanel5.add(jTextField19);

        jTextField20.setText("10%");
        jPanel5.add(jTextField20);

        jTextField21.setText("15%");
        jPanel5.add(jTextField21);

        jTextField22.setText("20%");
        jPanel5.add(jTextField22);

        jTextField23.setText("25%");
        jPanel5.add(jTextField23);

        jTextField24.setText("30%");
        jPanel5.add(jTextField24);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(7, 0));

        jLabel5.setText("SOBRE EXCESO");
        jPanel6.add(jLabel5);

        jTextField25.setText("0.00");
        jPanel6.add(jTextField25);

        jTextField26.setText("75000.00");
        jPanel6.add(jTextField26);

        jTextField27.setText("100000.00");
        jPanel6.add(jTextField27);

        jTextField28.setText("200000.00");
        jPanel6.add(jTextField28);

        jTextField29.setText("300000.00");
        jPanel6.add(jTextField29);

        jTextField30.setText("500000.00");
        jPanel6.add(jTextField30);

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tablair dialog = new tablair(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
